version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hedghog1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runsslserver --cert cert.pem --key key-no-pass.pem 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=hedghog_project.settings
      - DATABASE_URL=postgres://postgres:postgrespw@db:5432/hedghog1