# Generated by Django 4.2.1 on 2023-05-16 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number_home', models.TextField(blank=True, null=True)),
                ('phone_number_mobile', models.TextField(blank=True, null=True)),
                ('opted_out', models.BooleanField(default=False)),
                ('carer_status_id', models.IntegerField()),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('patient_status', models.TextField()),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_timestamp', models.DateTimeField()),
                ('weight_grams', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('carer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.carer')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
